apiVersion: v1
kind: Service
metadata:
  name: valkey-headless
  namespace: valkey
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
    - name: sentinel
      port: 26379
      targetPort: 26379
