apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cache
  name: cache
  namespace: valkey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: valkey
  serviceName: valkey-headless
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - image: valkey/valkey
          name: valkey
          command: ["/bin/sh", "/etc/valkey-readonly/startup/start-valkey.sh"]
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: startup-script
              mountPath: /etc/valkey-readonly/startup
            - name: valkey-config
              mountPath: /etc/valkey-readonly/config
            - name: valkey-data
              mountPath: /var/lib/valkey
          readinessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            timeoutSeconds: 2
            periodSeconds: 2
          startupProbe:
            exec:
              command: ["valkey-cli", "ping"]
            failureThreshold: 30
            timeoutSeconds: 2
            periodSeconds: 2
        - image: valkey/valkey
          name: valkey-sentinel
          command: ["/bin/sh", "/etc/valkey-readonly/startup/start-sentinel.sh"]
          volumeMounts:
            - name: startup-script
              mountPath: /etc/valkey-readonly/startup
            - name: sentinel-data
              mountPath: /var/lib/sentinel
          ports:
            - containerPort: 26379
              protocol: TCP
      volumes:
        - name: startup-script
          configMap:
            name: valkey-startup-script
        - name: valkey-config
          configMap:
            name: valkey-config
        - name: valkey-data
          emptyDir: {}
        - name: sentinel-data
          emptyDir: {}