name: Helm Template All Charts

on:
  push:
    branches: [ main, master, '*' ]
  pull_request:
    branches: [ main, master, '*' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  helm-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kube: ["1.31.0", "1.30.0"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # only current commit

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.3

      - name: Build chart dependencies
        run: |
          for chart in charts/*; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Building deps for $chart"
              helm dependency build "$chart" || true
            fi
          done

      - name: Render charts with helm template
        run: |
          mkdir -p /tmp/rendered
          for chart in charts/*; do
            if [ -f "$chart/Chart.yaml" ]; then
              out="/tmp/rendered/$(basename "$chart")-k${{ matrix.kube }}.yaml"
              echo "Rendering $chart -> $out"
              helm template "tmpl-${RANDOM}" "$chart" \
                --kube-version "${{ matrix.kube }}" \
                > "$out"
            fi
          done

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: helm-template-k${{ matrix.kube }}
          path: /tmp/rendered/*.yaml
  